# Generated by Django 5.1.6 on 2026-03-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0004_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="application_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="max_participants",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
