# Generated by Django 5.1.6 on 2026-03-09 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0005_hackathon_application_deadline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="hackathons.hackathon",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResultEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.PositiveSmallIntegerField()),
                ("project_name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("repo_url", models.URLField(blank=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="hackathons.hackathon",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="hackathons.team",
                    ),
                ),
            ],
            options={
                "ordering": ["place", "id"],
                "unique_together": {("hackathon", "place")},
            },
        ),
    ]
