# Generated by Django 5.1.6 on 2026-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0007_projectsubmission_juryscore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="juryscore",
            name="score",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
